Repository FIS2425/authorization-svc, pull requests merged in 2025-01, with the labels that each got.

#101 v1.1.5
  .env.example
  kubernetes/authorization-svc-deployment.yaml
  package-lock.json
  package.json
  src/controllers/userController.js
  src/utils/generateTokens.js
  tests/unit/controllers/userController.test.js
Labels: 📦 Dependencies, 🧪 Tests, ⚙️ Configuration, size/s

#102 chore: updated user populator to add patients
  populators/User.js
Labels: size/s

#103 v1.1.6
  src/api.js
  src/config/logger.js
  src/utils/kafkaTransport.js
Labels: size/s

#104 config: added workflow to deploy in aks
  .github/workflows/deploy-to-aks.yaml
Labels: 🚀 CI/CD, size/s

#105 fix: added dev cookie and secure cookie to docker compose
  docker-compose.yml
Labels: 🐳 Build, size/xs

#108 v1.1.7
  .github/workflows/deploy-to-aks.yaml
  docker-compose.yml
  kubernetes/authorization-svc-service.yaml
  populators/Role.js
Labels: 🚀 CI/CD, size/s, 🐳 Build

#109 v1.2.0
  src/utils/generateTokens.js
Labels: size/xs
